apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kafka.fullname" . }}-init-scripts
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-scripts
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/bash", "/init-scripts/init.sh"]
          env:
            - name: BOOTSTRAP_SERVER
              value: {{ .Values.service.name }}:{{ .Values.service.port }}
          volumeMounts:
            - name: init-scripts
              mountPath: /init-scripts
              readOnly: true
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "kafka.fullname" . }}-init-scripts
            defaultMode: 0755
